algoritmo "Caixa"
var
arroz: inteiro
feijao: inteiro
picanha: inteiro
spaten: inteiro
heineken: inteiro

inicio
Escreval("=========================")
Escreval("  Supermercado Prezunic  ")
Escreval("=========================")
Escreva("Arroz: R$")
Leia(arroz)
Escreva("Feijão: R$")
Leia(feijao)
Escreva("Picanha: R$")
Leia(picanha)
Escreva("Spaten: R$")
Leia(spaten)
Escreva("Heineken: R$")
Leia(heineken)
Escreval("-------------------------")
Escreval("         Resumo          ")
Escreva("Valor total: R$")
Escreval(arroz+picanha+feijao+spaten+heineken)
Escreva("Média dos produtos: R$")
EScreval((arroz+picanha+feijao+spaten+heineken)/5)
Escreva("3x s/ juros: R$")
Escreval((arroz+picanha+feijao+spaten+heineken)/3)
Escreval("=========================")
fimalgoritmo